### ISSUE TITLE
crush damage is contagious

### ISSUE THREAD

**Issue by SpannerMonkey** [gomker/HullBreach#7]
Scenario 
6 ships, 3 per team,  distance 2km.  Trigger guard mode and wait till first vessel sinks due to damage. switch to closest vessel to sinking vessel and switch guard mode off for all combatants (peace mode), so no further damage is sustained.  Observe behaviour, the sinking vessel breaks up as it should and starts to suffer crush damage, on the first warning, displayed on screen no matter which of the remaining 5 vessels you are viewing, all the remaining ships start to suffer damage to those parts that are marked as crushable, so mainly hull parts. This process continues until all vessels are completely destroyed.
Further testing continues

**Comment by gomker** [comment]
Part of me wonders if this is going to be one of those issues that manifests with a Part Module and the bleeding of values over like I am seeing in Airpark. I hope not as that will be more coding changes. Taking a look to see, if it is that I may need to disable crushing effect for now.

**Comment by gomker** [comment]
I think I tracked this down to some faulty logic in tracking the active vessel. Its doing a part loop and I can see where it would grab ALL parts regardless of status
